plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'com.modrinth.minotaur' version '2.+'
}

version = project.mod_version
group = project.maven_group

modrinth {
	token = System.getenv('MODRINTH_TOKEN')
	projectId = 'highlightmobs'
	versionNumber = "${project.mod_version}+${project.minecraft_version}"
	versionName = project.mod_version
	versionType = 'release'
	uploadFile = tasks.jar
	gameVersions = project.property('game_versions').toString().split(',').collect { it.trim() }
	loaders = ['fabric']
	dependencies {
		required.project 'fabric-api'
	}
}

base {
	archivesName = 'highlightmobs'
}

repositories {
	maven {
		name = 'Terraformers'
		url = 'https://maven.terraformersmc.com/releases/'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		highlightmobs {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}

def modVersion = project.version

processResources {
	inputs.property 'version', modVersion

	filesMatching('fabric.mod.json') {
		expand 'version': modVersion
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

def projectName = project.name

jar {
	from('LICENSE') {
		rename { "${it}_${projectName}" }
	}
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			from components.java
		}
	}
}
